  - name: Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: configmap.yml.j2
      apply: yes
    when: WITH_MESSENGER_SYNC
      
  - name: remove Configmap
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      state: absent
      api_version: v1
      kind: ConfigMap
      namespace: "{{ NAMESPACE }}"
      name: messenger-sync-configmap
    when: not WITH_MESSENGER_SYNC
      
  - name: remove Secret
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      api_version: v1
      kind: Secret
      namespace: "{{ NAMESPACE }}"
      name: messenger-sync-secret
    when: not WITH_MESSENGER_SYNC and ( ONEPASSWORD_OPERATOR is undefined or ( ONEPASSWORD_OPERATOR is defined and not ONEPASSWORD_OPERATOR ) )
      
  - name: Add or Update Secred by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: onepassword.yml.j2
    when: WITH_MESSENGER_SYNC and ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
      
  - name: remove Secred by 1Password
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      api_version: onepassword.com/v1
      kind: OnePasswordItem
      namespace: "{{ NAMESPACE }}"
      name: messenger-sync-secret
    when: not WITH_MESSENGER_SYNC and ONEPASSWORD_OPERATOR is defined and ONEPASSWORD_OPERATOR|bool
      
  - name: Add or Update Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config 
      namespace: "{{ NAMESPACE }}"
      template: deployment.yml.j2
    when: WITH_MESSENGER_SYNC 
      
  - name: remove Deployment
    kubernetes.core.k8s:
      kubeconfig: ~/.kube/config
      state: absent
      api_version: apps/v1
      kind: Deployment
      namespace: "{{ NAMESPACE }}"
      name: messenger-sync-deployment
    when: not WITH_MESSENGER_SYNC
